name: wide_decimal
on: [push,pull_request]
jobs:
  all-tests:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.commits[0].message, '[CI SKIP]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install g++-8
      - name: update-libboost-dev
        run: sudo apt install libboost-dev
      - name: update-libboost-all-dev
        run: sudo apt install libboost-all-dev
      - name: build-and-run-all-tests
        run: |
          echo "compile ./wide_decimal.exe"
          g++ -finline-functions -finline-limit=32 -march=native -mtune=native -O3 -Wall -Wextra -pedantic -Werror -Wno-cast-function-type -std=c++11 -I. -pthread -lpthread test/test.cpp test/test_decwide_t_algebra.cpp test/test_decwide_t_examples.cpp examples/example001_roots_sqrt.cpp examples/example001a_roots_seventh.cpp examples/example002_pi.cpp examples/example002a_pi_small_limb.cpp examples/example002b_pi_100k.cpp examples/example002c_pi_quintic.cpp examples/example003_zeta.cpp examples/example004_bessel_recur.cpp examples/example005_polylog_series.cpp examples/example006_logarithm.cpp examples/example007_catalan_series.cpp examples/example008_bernoulli_tgamma.cpp examples/example009_boost_math_standalone.cpp -o wide_decimal.exe
          echo "ls ./wide_decimal.exe"
          ls ./wide_decimal.exe
          ./wide_decimal.exe
          result_wide_decimal=$?
          echo "result_wide_decimal:"  "$result_wide_decimal"
          exit $result_wide_decimal
        shell: bash
